#!/usr/bin/env bash
set -euo pipefail

: "${GOOGLE_CLOUD_PROJECT:?Set GOOGLE_CLOUD_PROJECT}"
: "${GOOGLE_CLOUD_REGION:=us-central1}"
: "${CLICKHOUSE_HOST:?Set CLICKHOUSE_HOST}"
: "${CLICKHOUSE_USER:?Set CLICKHOUSE_USER}"
: "${SERVICE_ACCOUNT_EMAIL:?Set SERVICE_ACCOUNT_EMAIL}"

SERVICE_NAME="${SERVICE_NAME:-syncagent}"
CLICKHOUSE_PASSWORD_SECRET="${CLICKHOUSE_PASSWORD_SECRET:-syncagent-clickhouse-password}"

# Deploy with Cloud Run's service identity. Keep production secrets in Secret Manager.
gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --project "$GOOGLE_CLOUD_PROJECT" \
  --region "$GOOGLE_CLOUD_REGION" \
  --service-account "$SERVICE_ACCOUNT_EMAIL" \
  --set-env-vars "GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT,GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION:-us-central1},GOOGLE_GENAI_USE_VERTEXAI=TRUE,CLICKHOUSE_HOST=$CLICKHOUSE_HOST,CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8443},CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-default},CLICKHOUSE_USER=$CLICKHOUSE_USER,CORS_ORIGINS=${CORS_ORIGINS:-}" \
  --set-secrets "CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD_SECRET:latest" \
  "$@"
