"""Deterministic SyncAgent demo scenarios for API and presentation testing."""

SCENARIOS = [
    {"name": "Late Night Detective", "scene_description": "An exhausted detective walks through an empty Mumbai street at 2 AM after failing to solve a case.", "budget": 800, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Dark, slow candidates; rights failures remain visible.", "what_to_verify": ["scene analysis exists", "recommendations are rights-passing", "rejections retain reasons"]},
    {"name": "Romantic Dinner", "scene_description": "Two people share a quiet romantic dinner while rain moves across the restaurant windows.", "budget": 800, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Romantic piano, jazz, or orchestral candidates.", "what_to_verify": ["romantic mood", "moderate energy", "licensed recommendations"]},
    {"name": "Wedding Celebration", "scene_description": "Friends and family dance together under warm lights at a joyful wedding celebration.", "budget": 1000, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Happy, hopeful, energetic candidates.", "what_to_verify": ["upbeat tempo", "worldwide rights"]},
    {"name": "Action Chase", "scene_description": "A driver races through neon streets while two vehicles pursue him through tight turns.", "budget": 1000, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Fast electronic or suspense tracks.", "what_to_verify": ["high energy", "fast BPM", "rights filtering"]},
    {"name": "Horror Suspense", "scene_description": "A character hears footsteps in an empty house and slowly approaches a locked basement door.", "budget": 700, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Dark, tense, suspenseful candidates.", "what_to_verify": ["suspense genre", "rejection reasons"]},
    {"name": "Emotional Breakup", "scene_description": "After a breakup, a woman packs a suitcase alone in a quiet apartment at dawn.", "budget": 800, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Melancholic and intimate candidates.", "what_to_verify": ["slow tempo", "emotional instrumentation"]},
    {"name": "Hopeful Ending", "scene_description": "A survivor steps into morning sunlight and sees the city with renewed hope after a difficult journey.", "budget": 900, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Hopeful orchestral or ambient candidates.", "what_to_verify": ["hopeful mood", "positive ranking"]},
    {"name": "Documentary Montage", "scene_description": "A documentary montage shows people rebuilding a coastal community over several months.", "budget": 1000, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Cinematic, hopeful, adaptable tracks.", "what_to_verify": ["catalog search", "stable response contract"]},
    {"name": "Corporate Promotion", "scene_description": "A modern company unveils a clean new product to a confident, forward-looking audience.", "budget": 1000, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Energetic electronic or acoustic candidates.", "what_to_verify": ["commercial use", "worldwide territory"]},
    {"name": "Sports Victory", "scene_description": "A team celebrates a championship win with cheering supporters and exhausted players.", "budget": 1000, "territory": "Worldwide", "top_k": 5, "expected_behavior": "High-energy celebratory candidates.", "what_to_verify": ["fast BPM", "high energy"]},
    {"name": "Childhood Memory", "scene_description": "An adult remembers riding a bicycle with a parent through a sunny neighborhood during childhood.", "budget": 500, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Warm, nostalgic acoustic or piano candidates.", "what_to_verify": ["gentle mood", "affordable results"]},
    {"name": "Rainy City", "scene_description": "A solitary commuter watches rain blur the lights of a crowded city bus at night.", "budget": 800, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Urban, dark, ambient candidates.", "what_to_verify": ["urban atmosphere", "tempo fit"]},
    {"name": "Quiet Meditation", "scene_description": "A person sits beside a mountain lake at sunrise, breathing slowly and letting go of anxiety.", "budget": 300, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Peaceful low-energy ambient candidates.", "what_to_verify": ["low energy", "slow BPM"]},
    {"name": "Nightclub", "scene_description": "A group of friends enters a packed nightclub where the lights pulse with the beat.", "budget": 1200, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Fast, energetic electronic candidates.", "what_to_verify": ["high energy", "electronic genre"]},
    {"name": "No Match Budget", "scene_description": "A carefully composed melancholic night scene requires a polished licensed track, but the production has almost no music budget.", "budget": 50, "territory": "Worldwide", "top_k": 5, "expected_behavior": "No suitable recommendations; rejected candidates explain constraints.", "what_to_verify": ["empty recommendations are valid", "no fabricated tracks", "rejections are preserved"]},
    {"name": "Worldwide Licensing", "scene_description": "A film distributor prepares a global release montage with a broad cinematic emotional arc.", "budget": 1000, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Worldwide tracks only.", "what_to_verify": ["territory validation"]},
    {"name": "India Territory", "scene_description": "A reflective scene follows a family walking home through a familiar Indian neighborhood at dusk.", "budget": 700, "territory": "India", "top_k": 5, "expected_behavior": "Worldwide and India catalog records can pass; incompatible regions fail.", "what_to_verify": ["case-insensitive territory handling"]},
    {"name": "US Territory", "scene_description": "A tense legal drama scene ends with a lawyer leaving a courthouse in a storm.", "budget": 800, "territory": "US", "top_k": 5, "expected_behavior": "US and worldwide records can pass.", "what_to_verify": ["territory filtering"]},
    {"name": "Commercial Production", "scene_description": "A polished launch film introduces a new electric vehicle through fast, confident city shots.", "budget": 1500, "territory": "Worldwide", "top_k": 5, "expected_behavior": "Commercial-use records only.", "what_to_verify": ["commercial rights validation"]},
    {"name": "Creative Fit But Failed Rights", "scene_description": "A detective discovers a hidden clue while a dark, slow, emotionally restrained score should build tension.", "budget": 800, "territory": "Worldwide", "top_k": 5, "expected_behavior": "High creative matches can still be rejected for cost or rights.", "what_to_verify": ["creative and rights scores remain separate", "rejected tracks never recommend"]},
]

SCENARIO_NAMES = [scenario["name"] for scenario in SCENARIOS]
